export const publicKey=`-----BEGIN PUBLIC KEY-----
MFswDQYJKoZIhvcNAQEBBQADSgAwRwJAYx+6tRkQ7f0QrpsKwYqSIDzC2anLiYoh
7man4QHBCbZR0M2/5LvE+5APHgJp7jqgUPIEM/mHFRHLTTNBgFp+ZwIDAQAB
-----END PUBLIC KEY-----`